services:
  backend:
    image: frebbers/game-together-backend:latest  # Pull from Docker Hub
    ports:
      - "5000:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]  # Check the /health endpoint
      interval: 30s  # Run the health check every 30 seconds
      retries: 3  # Retry 3 times before marking as unhealthy
      start_period: 10s  # Wait 10 seconds before starting health checks
      timeout: 5s  # Timeout for the health check (5 seconds)

  frontend:
    image: frebbers/game-together-frontend:latest  # Pull from Docker Hub
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
